### ISSUE TITLE
[Support] MIDI Serial device mapping backwards?

### ISSUE THREAD

**Issue by ChrisWeiss** [Deftaudio/Midi-boards#5] opened 2021-10-29 17:52 UTC
I've been running through the software installation steps per the PDF. I'm at the part where I need to configure the MIDI ports. The docs say:

List all devices and find /serial0 should be on AMA0; /serial1 should be ttyS0
`ls -lh /dev/*`

In my system, the ports appear to be swapped. I'm not entirely sure how to go about resolving this.

```
lrwxrwxrwx  1 root  root           5 Oct 24 21:34 /dev/serial0 -> ttyS0
lrwxrwxrwx  1 root  root           7 Oct 24 21:34 /dev/serial1 -> ttyAMA0
```

**Comment by Deftaudio** [comment] 2021-10-29 18:06
Hi Chris, 
check that this part is accurate in your config file:
` Serial MIDI
 enable_uart=1
 dtoverylay=pi3-miniuart-bt
 dtoverlay=midi-uart0
 `
and if so, just run TTYMIDI in the verbose mode to check that it actually receives any MIDI data: 

`ttymidi -s /dev/ttyAMA0 -b 38400 -v`

**Comment by ChrisWeiss** [comment] 2021-10-29 18:16
I need to craft together a MIDI cable with the TRS jacks to test.

This is my `/boot/config.txt`

```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=2
hdmi_mode=85

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
#dtparam=audio=on

# I2C DAC
dtoverlay=hifiberry-dac

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
enable_uart=1

# Serial MIDI
enable_uart=1
dtoverylay=pi3-miniuart-bt
dtoverlay=midi-uart0
```

**Comment by Deftaudio** [comment] 2021-10-29 18:22
The only minor thing I see is the duplicate of `enable_uart=1` line.

**Comment by ChrisWeiss** [comment] 2021-10-29 18:39
Ah, I think I found a typo - `dtoverylay=pi3-miniuart-bt` should be `dtoverlay=pi3-miniuart-bt`.

This is incorrect in the original PDF as well. It appears that fixing that typo has fixed the port assignments.

**Comment by ChrisWeiss** [comment] 2021-10-29 18:41
As an aside, if you're updating the document, you might want to update the command for 'list all devices...' from just `ls -lh /dev/*` to `ls -lh /dev/serial*`. It'll make for a much cleaner output to verify against.

**Closed** 2021-11-06 21:27 UTC
